UdaWave: src/modules/Song/Song.c File Reference
Song.c File Reference
Implementation of the functions from Song.h.
#include "Song.h"
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <ctype.h>
Functions
void modifySongsFile (Song songs[], int size)
This function updates the songs' file.
void addToSongsFile (Song *song)
This function adds a given song to the .csv user file.
void printAlbumsOfArtist (Song songs[], int currentSongsNumber)
This function searches all songs of an artist and it prints them on screen.
Song ** searchSong (Song song[], int size, int *finalSize, unsigned short int researchType, const char *researched)
Search for songs.
Song ** searchSongByCode (Song song[], int size, int *finalSize, const char *toSearch)
Search for the song with a given code.
Song ** searchSongByTitle (Song song[], int size, int *finalSize, const char *toSearch)
Search for songs with a given title.
Song ** searchSongByArtist (Song song[], int size, int *finalSize, const char *toSearch)
Search for songs of a given artist.
Song ** searchSongByAlbum (Song song[], int size, int *finalSize, const char *toSearch)
Search for songs of a given album.
Song ** searchSongByGenre (Song song[], int size, int *finalSize, const char *toSearch)
Search for songs of a given genre.
void printSongsArray (Song *songs[], int size)
Print an array of songs.
void printSongToScreen (Song *song)
Print a song to screen.
int loadSongsFromFile (const char *path, Song array[], int maxSize)
This function loads songs' data from a file.
void searchForSongs (Song songs[], int songsNumber)
This function asks the user if he/she wants to search a song by title or by code, then it searches for a song.
void printCatalog (Song songs[], int songsNumber)
This function prints the whole catalog to screen.
void showSongsOfAlbum (Song songs[], int currentSongsNumber)
This function prints all songs of an album.
void insertDuration (struct Duration *duration)
This function inserts a duration.
void quicksort (Song **array, int inf, int sup, int sortBy)
This function sorts an array of integers using the quicksort algorithm (for more basic informations about this or other types of sorting algorithms, you can visit Wikipedia).
int partitionByDuration (Song **array, int inf, int sup)
This function is used by the quicksort algorithm, that sorts an array of Songs based on their duration.
int partitionByTrackNumber (Song **array, int inf, int sup)
This function is used by the quicksort algorithm, that sorts an array of Songs based on their track number in an album.
void swap (Song **a, Song **b)
This function swaps two given song's pointers.
bool isCodeValid (const char *code)
This function checks if a given string is formatted like a song code.
void insertCode (Song *songList, int size, char *code)
This function inserts a code.
Detailed Description
Implementation of the functions from Song.h.
This file contains the implementation of the function defined in Song.h. It uses the standard C libraries.
Version
0.1
Date
08/may/2018
Authors
Andrea Esposito, Graziano Montanaro
Copyright
No copyright informations provided.
Definition in file Song.c.
Function Documentation
addToSongsFile()
void addToSongsFile (Song * song)
This function adds a given song to the .csv user file.
Add a song to the songs' .csv file.
It uses a pointer to the song that it should save for optimization purposes.
Definition at line 59 of file Song.c.
References Song::albumName, Song::artist, Song::code, doesFileExists(), Song::duration, Song::genre, getMusicGenreName(), Song::Duration::min, Song::name, Song::Duration::sec, and Song::trackNumber.
Referenced by addSong().
insertCode()
void insertCode (Song * songList, int size, char * code)
This function inserts a code.
Insert the code of a song.
It waits for an input and if the given string is a valid code (if it is formatted like AB123), the function checks if the given code is already present in the songs list.
Definition at line 695 of file Song.c.
References isCodeValid(), and searchSong().
Referenced by addSong().
insertDuration()
void insertDuration (struct Duration * duration)
This function inserts a duration.
Insert a duration;.
Definition at line 537 of file Song.c.
References getChoice().
Referenced by addSong(), and modifySong().
isCodeValid()
bool isCodeValid (const char * code)
This function checks if a given string is formatted like a song code.
Check if a string is formatted like a code.
These codes are formatted like AB123.
Precondition
code should be a valid string.
Definition at line 682 of file Song.c.
References checkWithRegEx().
Referenced by insertCode().
loadSongsFromFile()
int loadSongsFromFile (const char * path, Song array[], int maxSize)
This function loads songs' data from a file.
Load songs' datas from file.
The informations are stored in an array (a void array, so that it can be used for various data structures).
Precondition
the file should exist.
Postcondition
If the file doesn't exist the function will close the program returning an error.
Definition at line 434 of file Song.c.
References doesFileExists(), Song::duration, Song::genre, getMusicGenreIndex(), MAX_CODE_LENGTH, MAX_SONGS_NUMBER, MAX_STRING_LENGTH, Song::Duration::min, Song::Duration::sec, and Song::trackNumber.
Referenced by main().
modifySongsFile()
void modifySongsFile (Song songs[], int size)
This function updates the songs' file.
Update users' file.
Definition at line 21 of file Song.c.
References getMusicGenreName().
Referenced by modifySong().
partitionByDuration()
int partitionByDuration (Song ** array, int inf, int sup)
This function is used by the quicksort algorithm, that sorts an array of Songs based on their duration.
Sort a partition of an array This function is used to sort a partition of an array of Songs.
Precondition
array is the array that has to be ordered (pointer to the first integer).
inf has to be 0 at the first call.
sup has to be the size of array decremented of one (using pseudo-code: array.size - 1).
Definition at line 609 of file Song.c.
References Song::duration, Song::Duration::min, Song::Duration::sec, and swap().
Referenced by quicksort().
partitionByTrackNumber()
int partitionByTrackNumber (Song ** array, int inf, int sup)
This function is used by the quicksort algorithm, that sorts an array of Songs based on their track number in an album.
Sort a partition of an array This function is used to sort a partition of an array of Songs.
Precondition
array is the array that has to be ordered (pointer to the first integer).
inf has to be 0 at the first call.
sup has to be the size of array decremented of one (using pseudo-code: array.size - 1).
Definition at line 641 of file Song.c.
References swap(), and Song::trackNumber.
Referenced by quicksort().
printAlbumsOfArtist()
void printAlbumsOfArtist (Song songs[], int currentSongsNumber)
This function searches all songs of an artist and it prints them on screen.
Print all albums of an artist.
Definition at line 96 of file Song.c.
References searchSongByArtist().
Referenced by main().
printCatalog()
void printCatalog (Song songs[], int songsNumber)
This function prints the whole catalog to screen.
Print all songs in the catalog.
Definition at line 510 of file Song.c.
References printSongsArray().
Referenced by main().
printSongsArray()
void printSongsArray (Song * songs[], int size)
Print an array of songs.
This function prints an array of songs using the function printsongToScreen.
Definition at line 385 of file Song.c.
References printSongToScreen().
Referenced by addFavourite(), addPlaylist(), addSongToPlaylist(), modifySong(), printCatalog(), printSongsOfGenre(), removeFavourite(), removeSongFromPlaylist(), searchForSongs(), and showSongsOfAlbum().
printSongToScreen()
void printSongToScreen (Song * song)
Print a song to screen.
This function prints all values of a song to screen.
Definition at line 408 of file Song.c.
References Song::albumName, Song::artist, Song::code, Song::duration, Song::genre, getMusicGenreName(), Song::Duration::min, Song::name, Song::Duration::sec, and Song::trackNumber.
Referenced by addFavourite(), printSongsArray(), removeFavourite(), and removeSongFromPlaylist().
quicksort()
void quicksort (Song ** array, int inf, int sup, int sortBy)
This function sorts an array of integers using the quicksort algorithm (for more basic informations about this or other types of sorting algorithms, you can visit Wikipedia).
Sort an array This function sorts an array of Songs.
Precondition
array is the array that has to be ordered (pointer to the first integer).
inf has to be 0 at the first call.
sup has to be the size of array decremented of one (using pseudo-code: array.size - 1).
Definition at line 571 of file Song.c.
References partitionByDuration(), partitionByTrackNumber(), and quicksort().
Referenced by printSongsOfGenre(), quicksort(), and showSongsOfAlbum().
searchForSongs()
void searchForSongs (Song songs[], int songsNumber)
This function asks the user if he/she wants to search a song by title or by code, then it searches for a song.
Search for a song.
Definition at line 484 of file Song.c.
References getInt(), printSongsArray(), and searchSong().
Referenced by main().
searchSong()
Song** searchSong (Song song[], int size, int * finalSize, unsigned short int researchType, const char * researched)
Search for songs.
Search songs.
Based on the value of researchType, this function searches by different properties of a song. To use this function properly, please refer to this table.
researchType Search by...
1 code
2 title
3 artist
4 album
5 genre
Definition at line 137 of file Song.c.
References searchSongByAlbum(), searchSongByArtist(), searchSongByCode(), searchSongByGenre(), and searchSongByTitle().
Referenced by addFavourite(), addPlaylist(), addSongToPlaylist(), insertCode(), loadPlaylistsFromFile(), loadUsersFromFile(), modifySong(), printSongsOfGenre(), removeFavourite(), removeSongFromPlaylist(), searchForSongs(), and showSongsOfAlbum().
searchSongByAlbum()
Song** searchSongByAlbum (Song song[], int size, int * finalSize, const char * toSearch)
Search for songs of a given album.
Search songs by album.
If toSearch is an empty string, the function will ask the user to insert an album that will be searched. Otherwise, it will use the value of toSearch as key.
Definition at line 296 of file Song.c.
Referenced by searchSong().
searchSongByArtist()
Song** searchSongByArtist (Song song[], int size, int * finalSize, const char * toSearch)
Search for songs of a given artist.
Search songs by artist.
If toSearch is an empty string, the function will ask the user to insert an artist that will be searched. Otherwise, it will use the value of toSearch as key.
Definition at line 250 of file Song.c.
Referenced by printAlbumsOfArtist(), and searchSong().
searchSongByCode()
Song** searchSongByCode (Song song[], int size, int * finalSize, const char * toSearch)
Search for the song with a given code.
Search a song by code.
If toSearch is an empty string, the function will ask the user to insert a code that will be searched. Otherwise, it will use the value of toSearch as key.
Definition at line 172 of file Song.c.
Referenced by searchSong().
searchSongByGenre()
Song** searchSongByGenre (Song song[], int size, int * finalSize, const char * toSearch)
Search for songs of a given genre.
Search songs by genre.
If toSearch is an empty string, the function will ask the user to insert a genre that will be searched. Otherwise, it will use the value of toSearch as key.
Precondition
toSearch must bean empty string or a valid genre.
Definition at line 344 of file Song.c.
References getGenre(), and getMusicGenreIndex().
Referenced by searchSong().
searchSongByTitle()
Song** searchSongByTitle (Song song[], int size, int * finalSize, const char * toSearch)
Search for songs with a given title.
Search songs by title.
If toSearch is an empty string, the function will ask the user to insert a title that will be searched. Otherwise, it will use the value of toSearch as key.
Definition at line 204 of file Song.c.
Referenced by searchSong().
showSongsOfAlbum()
void showSongsOfAlbum (Song songs[], int currentSongsNumber)
This function prints all songs of an album.
Print all songs of an album.
Definition at line 525 of file Song.c.
References printSongsArray(), quicksort(), and searchSong().
Referenced by main().
swap()
void swap (Song ** a, Song ** b)
This function swaps two given song's pointers.
Swap two song's pointers.
Definition at line 668 of file Song.c.
Referenced by partitionByDuration(), and partitionByTrackNumber().