UdaWave: src/modules/Song/Song.h File Reference
Song.h File Reference
Functions to manipulate songs.
#include "../Utilities/Utilities.h"
Data Structures
struct Song
A song.
struct Song::Duration
A duration.
Macros
#define MAX_SONGS_NUMBER 50
The maximum number of songs the software can manage.
Typedefs
typedef struct Song Song
A song.
Functions
Song ** searchSong (Song song[], int size, int *finalSize, unsigned short int researchType, const char *researched)
Search songs.
Song ** searchSongByCode (Song song[], int size, int *finalSize, const char *toSearch)
Search a song by code.
Song ** searchSongByTitle (Song song[], int size, int *finalSize, const char *toSearch)
Search songs by title.
Song ** searchSongByArtist (Song song[], int size, int *finalSize, const char *toSearch)
Search songs by artist.
Song ** searchSongByAlbum (Song song[], int size, int *finalSize, const char *toSearch)
Search songs by album.
Song ** searchSongByGenre (Song song[], int size, int *finalSize, const char *toSearch)
Search songs by genre.
void printSongsArray (Song *songs[], int size)
Print an array of songs.
void printSongToScreen (Song *song)
Print a song to screen.
void searchForSongs (Song songs[], int songsNumber)
Search for a song.
void printCatalog (Song songs[], int songsNumber)
Print all songs in the catalog.
void showSongsOfAlbum (Song songs[], int currentSongsNumber)
Print all songs of an album.
void printAlbumsOfArtist (Song songs[], int currentSongsNumber)
Print all albums of an artist.
bool isCodeValid (const char *code)
Check if a string is formatted like a code.
void insertCode (Song *songList, int size, char *code)
Insert the code of a song.
int loadSongsFromFile (const char *path, Song array[], int maxSize)
Load songs' datas from file.
void insertDuration (struct Duration *duration)
Insert a duration;.
void addToSongsFile (Song *song)
Add a song to the songs' .csv file.
void modifySongsFile (Song songs[], int size)
Update users' file.
void quicksort (Song **array, int inf, int sup, int sortBy)
Sort an array This function sorts an array of Songs.
int partitionByDuration (Song **array, int inf, int sup)
Sort a partition of an array This function is used to sort a partition of an array of Songs.
int partitionByTrackNumber (Song **array, int inf, int sup)
Sort a partition of an array This function is used to sort a partition of an array of Songs.
void swap (Song **a, Song **b)
Swap two song's pointers.
Detailed Description
Functions to manipulate songs.
This library contains functions that work on songs and songs' arrays, Along with the definitions of songs-related data structures. Some of this functions are based on functions defined in Utilities.h.
Version
0.1
Date
08/may/2018
Authors
Andrea Esposito, Graziano Montanaro
Copyright
No copyright informations provided.
Definition in file Song.h.
Macro Definition Documentation
MAX_SONGS_NUMBER
#define MAX_SONGS_NUMBER 50
The maximum number of songs the software can manage.
Definition at line 23 of file Song.h.
Referenced by addPlaylist(), addSong(), addSongToPlaylist(), loadPlaylistsFromFile(), loadSongsFromFile(), loadUsersFromFile(), and main().
Typedef Documentation
Song
typedef struct Song Song
A song.
This data structure contains all the informations about a song.
Function Documentation
addToSongsFile()
void addToSongsFile (Song * song)
Add a song to the songs' .csv file.
Parameters
[in] song Song to add to the file.
Add a song to the songs' .csv file.
It uses a pointer to the song that it should save for optimization purposes.
Definition at line 59 of file Song.c.
References Song::albumName, Song::artist, Song::code, doesFileExists(), Song::duration, Song::genre, getMusicGenreName(), Song::Duration::min, Song::name, Song::Duration::sec, and Song::trackNumber.
Referenced by addSong().
insertCode()
void insertCode (Song * songList, int size, char * code)
Insert the code of a song.
Parameters
[in] songList A list of songs.
[in] size The number of songs in the list.
[out] code The code that will be inserted.
Insert the code of a song.
It waits for an input and if the given string is a valid code (if it is formatted like AB123), the function checks if the given code is already present in the songs list.
Definition at line 695 of file Song.c.
References isCodeValid(), and searchSong().
Referenced by addSong().
insertDuration()
void insertDuration (struct Duration * duration)
Insert a duration;.
Parameters
[in] duration Pointer to where the duration will be saved.
Insert a duration;.
Definition at line 537 of file Song.c.
References getChoice().
Referenced by addSong(), and modifySong().
isCodeValid()
bool isCodeValid (const char * code)
Check if a string is formatted like a code.
Parameters
[in] code The string to check.
Returns
true if it is formatted like a code, false otherwise.
Check if a string is formatted like a code.
These codes are formatted like AB123.
Precondition
code should be a valid string.
Definition at line 682 of file Song.c.
References checkWithRegEx().
Referenced by insertCode().
loadSongsFromFile()
int loadSongsFromFile (const char * path, Song array[], int maxSize)
Load songs' datas from file.
Parameters
[in] path The path of the file.
[in] array The array where datas should be saved.
[in] maxSize The maximum size of the array.
Returns
The function returns the number of read elements. It return -1 in case of any error.
Load songs' datas from file.
The informations are stored in an array (a void array, so that it can be used for various data structures).
Precondition
the file should exist.
Postcondition
If the file doesn't exist the function will close the program returning an error.
Definition at line 434 of file Song.c.
References doesFileExists(), Song::duration, Song::genre, getMusicGenreIndex(), MAX_CODE_LENGTH, MAX_SONGS_NUMBER, MAX_STRING_LENGTH, Song::Duration::min, Song::Duration::sec, and Song::trackNumber.
Referenced by main().
modifySongsFile()
void modifySongsFile (Song songs[], int size)
Update users' file.
Parameters
[in] songs The array of users.
[in] size The size of the users' array.
Update users' file.
Definition at line 21 of file Song.c.
References getMusicGenreName().
Referenced by modifySong().
partitionByDuration()
int partitionByDuration (Song ** array, int inf, int sup)
Sort a partition of an array This function is used to sort a partition of an array of Songs.
Parameters
[in] array Array that has to be ordered (pointer to the first integer).
[in] inf Inferior index.
[in] sup Superior index.
Returns
pivot's new position (after the execution of the function).
Sort a partition of an array This function is used to sort a partition of an array of Songs.
Precondition
array is the array that has to be ordered (pointer to the first integer).
inf has to be 0 at the first call.
sup has to be the size of array decremented of one (using pseudo-code: array.size - 1).
Definition at line 609 of file Song.c.
References Song::duration, Song::Duration::min, Song::Duration::sec, and swap().
Referenced by quicksort().
partitionByTrackNumber()
int partitionByTrackNumber (Song ** array, int inf, int sup)
Sort a partition of an array This function is used to sort a partition of an array of Songs.
Parameters
[in] array Array that has to be ordered (pointer to the first integer).
[in] inf Inferior index.
[in] sup Superior index.
Returns
pivot's new position (after the execution of the function).
Sort a partition of an array This function is used to sort a partition of an array of Songs.
Precondition
array is the array that has to be ordered (pointer to the first integer).
inf has to be 0 at the first call.
sup has to be the size of array decremented of one (using pseudo-code: array.size - 1).
Definition at line 641 of file Song.c.
References swap(), and Song::trackNumber.
Referenced by quicksort().
printAlbumsOfArtist()
void printAlbumsOfArtist (Song songs[], int currentSongsNumber)
Print all albums of an artist.
Parameters
[in] songs The list of songs.
[in] currentSongsNumber The size of the list of songs.
Print all albums of an artist.
Definition at line 96 of file Song.c.
References searchSongByArtist().
Referenced by main().
printCatalog()
void printCatalog (Song songs[], int songsNumber)
Print all songs in the catalog.
Parameters
[in] songs The list of songs.
[in] songsNumber The size of the list of songs.
Print all songs in the catalog.
Definition at line 510 of file Song.c.
References printSongsArray().
Referenced by main().
printSongsArray()
void printSongsArray (Song * songs[], int size)
Print an array of songs.
Parameters
[in] songs The array of songs.
[in] size The size of the array of songs.
This function prints an array of songs using the function printsongToScreen.
Definition at line 385 of file Song.c.
References printSongToScreen().
Referenced by addFavourite(), addPlaylist(), addSongToPlaylist(), modifySong(), printCatalog(), printSongsOfGenre(), removeFavourite(), removeSongFromPlaylist(), searchForSongs(), and showSongsOfAlbum().
printSongToScreen()
void printSongToScreen (Song * song)
Print a song to screen.
Parameters
[in] song The song that will be printed.
This function prints all values of a song to screen.
Definition at line 408 of file Song.c.
References Song::albumName, Song::artist, Song::code, Song::duration, Song::genre, getMusicGenreName(), Song::Duration::min, Song::name, Song::Duration::sec, and Song::trackNumber.
Referenced by addFavourite(), printSongsArray(), removeFavourite(), and removeSongFromPlaylist().
quicksort()
void quicksort (Song ** array, int inf, int sup, int sortBy)
Sort an array This function sorts an array of Songs.
Parameters
[in] array Array that has to be ordered (pointer to the first Song).
[in] inf Inferior index.
[in] sup Superior index.
[in] sortBy Choose 0 if it has to sort by duration, 1 if it has to sort by track number.
Returns
void.
Sort an array This function sorts an array of Songs.
Precondition
array is the array that has to be ordered (pointer to the first integer).
inf has to be 0 at the first call.
sup has to be the size of array decremented of one (using pseudo-code: array.size - 1).
Definition at line 571 of file Song.c.
References partitionByDuration(), partitionByTrackNumber(), and quicksort().
Referenced by printSongsOfGenre(), quicksort(), and showSongsOfAlbum().
searchForSongs()
void searchForSongs (Song songs[], int songsNumber)
Search for a song.
Parameters
[in] songs The list of songs.
[in] songsNumber The size of the list of songs.
Search for a song.
Definition at line 484 of file Song.c.
References getInt(), printSongsArray(), and searchSong().
Referenced by main().
searchSong()
Song** searchSong (Song song[], int size, int * finalSize, unsigned short int researchType, const char * researched)
Search songs.
Parameters
[in] song The list of songs.
[in] size The size of the list of songs.
[out] finalSize Where to store the number of found songs.
[in] researchType The type of search that will be used (by title, by code, etc.).
[in] researched The search parameter (it can be an empty string).
Returns
An array of pointer to songs.
Search songs.
Based on the value of researchType, this function searches by different properties of a song. To use this function properly, please refer to this table.
researchType Search by...
1 code
2 title
3 artist
4 album
5 genre
Definition at line 137 of file Song.c.
References searchSongByAlbum(), searchSongByArtist(), searchSongByCode(), searchSongByGenre(), and searchSongByTitle().
Referenced by addFavourite(), addPlaylist(), addSongToPlaylist(), insertCode(), loadPlaylistsFromFile(), loadUsersFromFile(), modifySong(), printSongsOfGenre(), removeFavourite(), removeSongFromPlaylist(), searchForSongs(), and showSongsOfAlbum().
searchSongByAlbum()
Song** searchSongByAlbum (Song song[], int size, int * finalSize, const char * toSearch)
Search songs by album.
Parameters
[in] song The list of songs.
[in] size The size of the list of songs.
[out] finalSize Where to store the number of found songs.
[in] toSearch The search parameter.
Returns
An array of pointer to songs.
Search songs by album.
If toSearch is an empty string, the function will ask the user to insert an album that will be searched. Otherwise, it will use the value of toSearch as key.
Definition at line 296 of file Song.c.
Referenced by searchSong().
searchSongByArtist()
Song** searchSongByArtist (Song song[], int size, int * finalSize, const char * toSearch)
Search songs by artist.
Parameters
[in] song The list of songs.
[in] size The size of the list of songs.
[out] finalSize Where to store the number of found songs.
[in] toSearch The search parameter.
Returns
An array of pointer to songs.
Search songs by artist.
If toSearch is an empty string, the function will ask the user to insert an artist that will be searched. Otherwise, it will use the value of toSearch as key.
Definition at line 250 of file Song.c.
Referenced by printAlbumsOfArtist(), and searchSong().
searchSongByCode()
Song** searchSongByCode (Song song[], int size, int * finalSize, const char * toSearch)
Search a song by code.
Parameters
[in] song The list of songs.
[in] size The size of the list of songs.
[out] finalSize Where to store the number of found songs.
[in] toSearch The search parameter.
Returns
An array of pointer to songs.
Search a song by code.
If toSearch is an empty string, the function will ask the user to insert a code that will be searched. Otherwise, it will use the value of toSearch as key.
Definition at line 172 of file Song.c.
Referenced by searchSong().
searchSongByGenre()
Song** searchSongByGenre (Song song[], int size, int * finalSize, const char * toSearch)
Search songs by genre.
Parameters
[in] song The list of songs.
[in] size The size of the list of songs.
[out] finalSize Where to store the number of found songs.
[in] toSearch The search parameter.
Returns
An array of pointer to songs.
Search songs by genre.
If toSearch is an empty string, the function will ask the user to insert a genre that will be searched. Otherwise, it will use the value of toSearch as key.
Precondition
toSearch must bean empty string or a valid genre.
Definition at line 344 of file Song.c.
References getGenre(), and getMusicGenreIndex().
Referenced by searchSong().
searchSongByTitle()
Song** searchSongByTitle (Song song[], int size, int * finalSize, const char * toSearch)
Search songs by title.
Parameters
[in] song The list of songs.
[in] size The size of the list of songs.
[out] finalSize Where to store the number of found songs.
[in] toSearch The search parameter.
Returns
An array of pointer to songs.
Search songs by title.
If toSearch is an empty string, the function will ask the user to insert a title that will be searched. Otherwise, it will use the value of toSearch as key.
Definition at line 204 of file Song.c.
Referenced by searchSong().
showSongsOfAlbum()
void showSongsOfAlbum (Song songs[], int currentSongsNumber)
Print all songs of an album.
Parameters
[in] songs The list of songs.
[in] currentSongsNumber The size of the list of songs.
Print all songs of an album.
Definition at line 525 of file Song.c.
References printSongsArray(), quicksort(), and searchSong().
Referenced by main().
swap()
void swap (Song ** a, Song ** b)
Swap two song's pointers.
This function swaps two given integers.
Parameters
[in] a First pointer to swap with second.
[in] b Second pointer to swap with first.
Swap two song's pointers.
Definition at line 668 of file Song.c.
Referenced by partitionByDuration(), and partitionByTrackNumber().