UdaWave: src/modules/Testing/Testing.c File Reference
Testing.c File Reference
Test functions.
#include "Testing.h"
Functions
int init_suite_dafault ()
int clean_suite_dafault ()
void test_isNameValid ()
void test_isMailValid ()
void test_isDateValid ()
void test_getMusicGenreName ()
void test_getMusicGenreIndex ()
void test_isLeapYear ()
int testingMain ()
Detailed Description
Test functions.
This file contains the implementation of the functions defined in Testing.h.
Version
0.1
Date
29/may/2018
Authors
Andrea Esposito, Graziano Montanaro
Copyright
No copyright informations provided.
Definition in file Testing.c.
Function Documentation
clean_suite_dafault()
int clean_suite_dafault ()
Definition at line 23 of file Testing.c.
Referenced by testingMain().
init_suite_dafault()
int init_suite_dafault ()
Definition at line 16 of file Testing.c.
Referenced by testingMain().
test_getMusicGenreIndex()
void test_getMusicGenreIndex ()
Definition at line 75 of file Testing.c.
References getMusicGenreIndex().
Referenced by testingMain().
test_getMusicGenreName()
void test_getMusicGenreName ()
Definition at line 63 of file Testing.c.
References getMusicGenreName().
Referenced by testingMain().
test_isDateValid()
void test_isDateValid ()
Definition at line 51 of file Testing.c.
References isDateValid().
Referenced by testingMain().
test_isLeapYear()
void test_isLeapYear ()
Definition at line 87 of file Testing.c.
References isLeapYear().
Referenced by testingMain().
test_isMailValid()
void test_isMailValid ()
Definition at line 39 of file Testing.c.
References isMailValid().
Referenced by testingMain().
test_isNameValid()
void test_isNameValid ()
Definition at line 27 of file Testing.c.
References isNameValid().
Referenced by testingMain().
testingMain()
int testingMain ()
Definition at line 99 of file Testing.c.
References clean_suite_dafault(), init_suite_dafault(), test_getMusicGenreIndex(), test_getMusicGenreName(), test_isDateValid(), test_isLeapYear(), test_isMailValid(), and test_isNameValid().
Referenced by main().