UdaWave: src/UdaWave.c File Reference
UdaWave.c File Reference
Main file of the project.
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <ctype.h>
#include "modules/Song/Song.h"
#include "modules/User/User.h"
#include "modules/Testing/Testing.h"
Functions
int addSong (Song songs[], int *currentSize, User *const *currentLoggedUser)
Add a song.
int modifySong (Song songs[], int currentSize, User *const *currentLoggedUser)
Modify a song.
int menu (User **currentLoggedUser)
Shows on screen a choice menu.
void setConsoleTitle (const char *newTitle)
Set the console title.
int main (void)
Entry point of the program.
Variables
const char * APP_NAME = "UdaWave"
The name of the project.
Detailed Description
Main file of the project.
This file contains the main function of the project, along with some functions that use types and functions defined in external libraries. It also contains some functions to customize the O.S. console.
Version
0.1
Date
A.A. 2017/2018
Authors
Andrea Esposito, Graziano Montanaro
Copyright
No copyright informations provided.
Definition in file UdaWave.c.
Function Documentation
addSong()
int addSong (Song songs[], int * currentSize, User *const * currentLoggedUser)
Add a song.
This function adds a song and it saves its datas in a file.
Parameters
[in] songs Array of songs.
[in] currentSize Pointer to the current dimension of the array.
[in] currentLoggedUser The current logged user.
Returns
The function returns the new dimension of the array if it succeed. If it fails, it returns -1.
Precondition
currentSize should be less than the maximum number of songs
Postcondition
If currentSize is greater than the maximum number of songs, the function fails and it returns -1.
Definition at line 374 of file UdaWave.c.
References addToSongsFile(), Song::genre, getChoice(), getGenre(), getInt(), insertCode(), insertDuration(), MAX_SONGS_NUMBER, and Song::trackNumber.
Referenced by main().
main()
int main (void)
Entry point of the program.
This is the entry point of the program. It creates the console window (and set its properties) and it defines all the important variables that will be used throughout the program.
Returns
If everything went well, it returns EXIT_SUCCESS (0)
Definition at line 117 of file UdaWave.c.
References addPlaylist(), addSong(), addSongToPlaylist(), addUser(), APP_NAME, getInt(), loadPlaylistsFromFile(), loadSongsFromFile(), loadUsersFromFile(), logIn(), logOut(), MAX_SONGS_NUMBER, MAX_USERS_NUMBER, menu(), modifyFavourites(), modifyPlaylist(), modifySong(), modifyUser(), User::name, printAlbumsOfArtist(), printCatalog(), printPlaylistsToScreen(), printPublicPlaylistsToScreen(), printSongsOfGenre(), printUsersArray(), removePlaylist(), removeSongFromPlaylist(), savePlaylistsToFile(), searchForSongs(), setConsoleTitle(), showSongsOfAlbum(), testingMain(), and writePlaylistToFile().
menu()
int menu (User ** currentLoggedUser)
Shows on screen a choice menu.
Returns
The function returns the number of the choice.
Asks the user to make a choice by inserting a value, checking the inserted value.
Definition at line 513 of file UdaWave.c.
References APP_NAME, and getInt().
Referenced by main().
modifySong()
int modifySong (Song songs[], int currentSize, User *const * currentLoggedUser)
Modify a song.
This function modify a song and it saves its datas in a file.
Parameters
[in] songs Array of songs.
[in] currentSize Current dimension of the array.
[in] currentLoggedUser The current logged user.
Returns
The function returns the new dimension of the array if it succeed. If it fails, it returns -1.
Definition at line 439 of file UdaWave.c.
References getGenre(), getInt(), insertDuration(), modifySongsFile(), printSongsArray(), and searchSong().
Referenced by main().
setConsoleTitle()
void setConsoleTitle (const char * newTitle)
Set the console title.
Set the console title using a given string.
Parameters
[in] newTitle The new title of the console.
Warning
This function uses instructions that only work on Windows O.S.
Definition at line 563 of file UdaWave.c.
Referenced by main().
Variable Documentation
APP_NAME
const char* APP_NAME = "UdaWave"
The name of the project.
This constant holds the name of the project, which is used by some functions to print it to the screen.
Definition at line 69 of file UdaWave.c.
Referenced by main(), and menu().