UdaWave: src/modules/User/User.c File Reference
User.c File Reference
Implementation of the functions from User.h.
#include "User.h"
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <ctype.h>
Functions
void printUsersArray (User *users[], int size)
Print an array of users to screen using the function printUserToScreen.
void printUserToScreen (User *user)
Print all data of a user to screen.
int getUserIdByNickname (User users[], int size)
This function gets the index of a user in an array.
void modifyFavourites (User **userToModify, User users[], int usersNumber, Song songs[], int songsNumber)
A function to modify the favorite list of a user.
void addFavourite (User **userToModify, User users[], int usersNumber, Song songs[], int songsNumber)
Called by modifyFavourites. Add a favorite to a user's favorite list.
void removeFavourite (User **userToModify, User users[], int usersNumber, Song songs[], int songsNumber)
Called by modifyFavourites. Remove a favorite from a user's favorite list.
int addUser (User users[], int *currentSize, User **currentLoggedUser)
This function adds a user and it saves its data in a file.
void addToUsersFile (User *user)
This function adds a given user to the .csv user file.
int searchInUsers (User users[], int size, const char *nickname)
This function finds the user with the given username.
int loadUsersFromFile (const char *path, Song *songs, int currentSongNumber, User array[], int maxSize)
This function loads users' data from a file.
void printSongsOfGenre (User users[], int usersNumber, User **currentLoggedUser)
This function gets and prints all the songs of a given genre to screen.
void printUsersList (User users[], int usersNumber)
This function prints all users to screen.
void savePlaylistsToFile (User users[], int usersNumber, User *const *currentLoggedUser)
Save all playlists of a user to a file.
void loadPlaylistsFromFile (User usersToModify[], int usersNumber, Song songs[], int currentSongsNumber)
Load all playists from a file.
void printPlaylistsToScreen (User *user)
This function prints all the informations of all the playlists of a user.
void addPlaylist (User *user, Song songs[], int currentSongSize)
This function creates and adds a new playlist to a user.
void removePlaylist (User *user, Song songs[], int currentSongSize)
This function removes a playlist from a user.
void modifyPlaylist (User *user, Song songs[], int currentSongSize)
This function gives the user the ability to modify one of his/her playlists.
void addSongToPlaylist (User *user, Song songs[], int currentSongSize)
This function adds a song to a playlist.
void removeSongFromPlaylist (User *user, Song songs[], int currentSongSize)
This function removes a song from a playlist.
User * logIn (User users[], int usersNumber)
This function asks for the login informations to the user, and eventually it logs in with the chosen account.
void logOut (User **currentLoggedUser)
This function gives the user the ability to log out immediately.
void modifyUser (User users[], int currentSize, User **currentLoggedUser)
This function gives the user the ability to modify his/her datas (except the username).
void modifyUsersFile (User users[], int size)
This function updates the users' file.
void writePlaylistToFile (User *user)
This function writes the data of all the playlists of a user to a .csv file.
void getNickname (User *usersList, int size, char *nickname)
This function inserts a nickname.
void printPublicPlaylistsToScreen (User user[], int usersNumber, User *currentLoggedUser)
Show all public playlists.
Playlist ** searchInPlaylists (User users[], int usersNumber, const char *playlistName, const char *ownerName)
Search for a playlist.
Detailed Description
Implementation of the functions from User.h.
This file contains the implementation of the function defined in User.h. It uses the standard C libraries, along with the custom libraries Utilities.h and Song.h.
Version
0.1
Date
08/may/2018
Authors
Andrea Esposito, Graziano Montanaro
Copyright
No copyright informations provided.
Definition in file User.c.
Function Documentation
addFavourite()
void addFavourite (User ** userToModify, User users[], int usersNumber, Song songs[], int songsNumber)
Called by modifyFavourites. Add a favorite to a user's favorite list.
Add a favourite to the favourite list.
Definition at line 117 of file User.c.
References getChoice(), getInt(), printSongsArray(), printSongToScreen(), and searchSong().
Referenced by modifyFavourites().
addPlaylist()
void addPlaylist (User * user, Song songs[], int currentSongSize)
This function creates and adds a new playlist to a user.
Add a playlist.
Definition at line 751 of file User.c.
References Song::code, User::favouriteSongs, getChoice(), getInt(), Playlist::isPrivate, MAX_PLAYLIST_NUMBER, MAX_SONGS_NUMBER, Playlist::name, User::nickname, User::numberOfPlaylists, Playlist::numberOfSongs, Playlist::ownerNickname, User::playlists, printSongsArray(), searchInPlaylists(), searchSong(), Playlist::songs, and writePlaylistToFile().
Referenced by main().
addSongToPlaylist()
void addSongToPlaylist (User * user, Song songs[], int currentSongSize)
This function adds a song to a playlist.
Add a song to a playlist.
Definition at line 977 of file User.c.
References User::favouriteSongs, getChoice(), getInt(), MAX_SONGS_NUMBER, User::nickname, printSongsArray(), searchInPlaylists(), searchSong(), and writePlaylistToFile().
Referenced by main().
addToUsersFile()
void addToUsersFile (User * user)
This function adds a given user to the .csv user file.
Add a user to the users' .csv file.
It uses a pointer to the user that it should save for optimization purposes.
Definition at line 299 of file User.c.
References User::birthDate, Song::code, Date::day, doesFileExists(), User::email, User::favouriteSongs, Date::month, User::name, User::nickname, User::numberOfFavouriteSongs, User::sex, User::surname, and Date::year.
Referenced by addUser().
addUser()
int addUser (User users[], int * currentSize, User ** currentLoggedUser)
This function adds a user and it saves its data in a file.
Add a user.
Precondition
currentSize should be less than the maximum number of users
Postcondition
If currentSize is greater than the maximum number of users, the function fails and it returns -1.
Definition at line 243 of file User.c.
References addToUsersFile(), User::birthDate, getDate(), getMail(), getName(), getNickname(), getSex(), MAX_USERS_NUMBER, User::numberOfFavouriteSongs, and User::sex.
Referenced by main().
getNickname()
void getNickname (User * usersList, int size, char * nickname)
This function inserts a nickname.
Insert a nickname;.
Definition at line 1303 of file User.c.
References searchInUsers().
Referenced by addUser().
getUserIdByNickname()
int getUserIdByNickname (User users[], int size)
This function gets the index of a user in an array.
Get the id of a user.
It searches using the nickname, so the function ask the user to insert one (and it checks if it's valid).
Definition at line 59 of file User.c.
References searchInUsers().
Referenced by logIn(), modifyUser(), printPublicPlaylistsToScreen(), printSongsOfGenre(), and savePlaylistsToFile().
loadPlaylistsFromFile()
void loadPlaylistsFromFile (User usersToModify[], int usersNumber, Song songs[], int currentSongsNumber)
Load all playists from a file.
Load all playlists from a file.
This function gets all the playlists from all users' file and load all the stored informations. Then, it eventually link shared playlists.
Definition at line 625 of file User.c.
References doesFileExists(), Playlist::isPrivate, MAX_CODE_LENGTH, MAX_PLAYLIST_NUMBER, MAX_SONGS_NUMBER, MAX_STRING_LENGTH, MAX_USERS_NUMBER, User::numberOfPlaylists, Playlist::numberOfSongs, User::playlists, searchInUsers(), searchSong(), and Playlist::songs.
Referenced by main().
loadUsersFromFile()
int loadUsersFromFile (const char * path, Song * songs, int currentSongNumber, User array[], int maxSize)
This function loads users' data from a file.
Load users' datas from file.
The informations are stored in an array (a void array, so that it can be used for various data structures).
Precondition
The file should exist.
Postcondition
If the file doesn't exist the function will return -1.
Definition at line 366 of file User.c.
References User::birthDate, Date::day, doesFileExists(), User::favouriteSongs, MAX_CODE_LENGTH, MAX_SONGS_NUMBER, MAX_STRING_LENGTH, Date::month, User::numberOfFavouriteSongs, searchInUsers(), searchSong(), User::sex, and Date::year.
Referenced by main().
logIn()
User* logIn (User users[], int usersNumber)
This function asks for the login informations to the user, and eventually it logs in with the chosen account.
Log a user in.
Definition at line 1150 of file User.c.
References User::email, getMail(), getUserIdByNickname(), and MAX_STRING_LENGTH.
Referenced by main().
logOut()
void logOut (User ** currentLoggedUser)
This function gives the user the ability to log out immediately.
Log out from current session.
Definition at line 1169 of file User.c.
Referenced by main().
modifyFavourites()
void modifyFavourites (User ** userToModify, User users[], int usersNumber, Song songs[], int songsNumber)
A function to modify the favorite list of a user.
Modify favourite list.
It asks the user if he/she wants to add or remove a song to/from their favorite list.
Definition at line 88 of file User.c.
References addFavourite(), getInt(), modifyUsersFile(), and removeFavourite().
Referenced by main().
modifyPlaylist()
void modifyPlaylist (User * user, Song songs[], int currentSongSize)
This function gives the user the ability to modify one of his/her playlists.
Remove a playlist.
Definition at line 909 of file User.c.
References getChoice(), User::nickname, searchInPlaylists(), and writePlaylistToFile().
Referenced by main().
modifyUser()
void modifyUser (User users[], int currentSize, User ** currentLoggedUser)
This function gives the user the ability to modify his/her datas (except the username).
Modify a user.
Definition at line 1181 of file User.c.
References User::birthDate, User::email, getDate(), getMail(), getName(), getSex(), getUserIdByNickname(), modifyUsersFile(), User::name, User::nickname, User::sex, and User::surname.
Referenced by main().
modifyUsersFile()
void modifyUsersFile (User users[], int size)
This function updates the users' file.
Update users' file.
Definition at line 1221 of file User.c.
Referenced by modifyFavourites(), and modifyUser().
printPlaylistsToScreen()
void printPlaylistsToScreen (User * user)
This function prints all the informations of all the playlists of a user.
Print a user's playlist's list to screen.
Definition at line 720 of file User.c.
References Song::artist, Playlist::isPrivate, Song::name, Playlist::name, User::name, User::numberOfPlaylists, Playlist::numberOfSongs, Playlist::ownerNickname, User::playlists, Playlist::songs, and User::surname.
Referenced by main().
printPublicPlaylistsToScreen()
void printPublicPlaylistsToScreen (User user[], int usersNumber, User * currentLoggedUser)
Show all public playlists.
This function gets and prints to screen all public playlists. Then it asks o the user if he/she wants to add one of those playist to his/her own playlists' list.
Definition at line 1329 of file User.c.
References getChoice(), getUserIdByNickname(), MAX_PLAYLIST_NUMBER, User::nickname, User::numberOfPlaylists, Playlist::numberOfSongs, User::playlists, and searchInPlaylists().
Referenced by main().
printSongsOfGenre()
void printSongsOfGenre (User users[], int usersNumber, User ** currentLoggedUser)
This function gets and prints all the songs of a given genre to screen.
Print all songs of a genre.
Definition at line 509 of file User.c.
References getUserIdByNickname(), User::nickname, User::numberOfFavouriteSongs, printSongsArray(), quicksort(), searchInUsers(), and searchSong().
Referenced by main().
printUsersArray()
void printUsersArray (User * users[], int size)
Print an array of users to screen using the function printUserToScreen.
Print all users data to screen.
Definition at line 22 of file User.c.
References printUserToScreen().
Referenced by main(), and printUsersList().
printUsersList()
void printUsersList (User users[], int usersNumber)
This function prints all users to screen.
Warning
This function will soon be removed.
Definition at line 555 of file User.c.
References printUsersArray().
printUserToScreen()
void printUserToScreen (User * user)
Print all data of a user to screen.
Print a single user to screen.
Definition at line 32 of file User.c.
References Song::artist, User::birthDate, Date::day, User::email, User::favouriteSongs, Date::month, Song::name, User::name, User::nickname, User::numberOfFavouriteSongs, User::sex, User::surname, and Date::year.
Referenced by printUsersArray().
removeFavourite()
void removeFavourite (User ** userToModify, User users[], int usersNumber, Song songs[], int songsNumber)
Called by modifyFavourites. Remove a favorite from a user's favorite list.
Remove a favourite from the favourite list.
Definition at line 173 of file User.c.
References getChoice(), getInt(), printSongsArray(), printSongToScreen(), and searchSong().
Referenced by modifyFavourites().
removePlaylist()
void removePlaylist (User * user, Song songs[], int currentSongSize)
This function removes a playlist from a user.
Remove a playlist.
Definition at line 857 of file User.c.
References Playlist::name, User::nickname, User::numberOfPlaylists, User::playlists, searchInPlaylists(), and writePlaylistToFile().
Referenced by main().
removeSongFromPlaylist()
void removeSongFromPlaylist (User * user, Song songs[], int currentSongSize)
This function removes a song from a playlist.
Remove a song from a playlist.
Definition at line 1063 of file User.c.
References getChoice(), getInt(), User::nickname, printSongsArray(), printSongToScreen(), searchInPlaylists(), searchSong(), and writePlaylistToFile().
Referenced by main().
savePlaylistsToFile()
void savePlaylistsToFile (User users[], int usersNumber, User *const * currentLoggedUser)
Save all playlists of a user to a file.
Saves all playlists of a user to file.
This function will work only if the current logged user is the admin. It will create a .csv file which name is the username of the user of whom the playlists will be printed.
Definition at line 571 of file User.c.
References getUserIdByNickname(), and MAX_STRING_LENGTH.
Referenced by main().
searchInPlaylists()
Playlist** searchInPlaylists (User users[], int usersNumber, const char * playlistName, const char * ownerName)
Search for a playlist.
Search a playlist.
This function searches trough all the playlists. A playlist is identified by its name and its owner's nickname. The function doesn't search only public or private playlists.
Precondition
The searched playlist should exist
Postcondition
If the playlist doesn't exist, the function will return a null pointer.
Definition at line 1420 of file User.c.
References User::numberOfPlaylists, and User::playlists.
Referenced by addPlaylist(), addSongToPlaylist(), modifyPlaylist(), printPublicPlaylistsToScreen(), removePlaylist(), and removeSongFromPlaylist().
searchInUsers()
int searchInUsers (User users[], int size, const char * nickname)
This function finds the user with the given username.
Find the user with the given username.
Postcondition
If the nickname isn't used, the function returns -1
Definition at line 343 of file User.c.
Referenced by getNickname(), getUserIdByNickname(), loadPlaylistsFromFile(), loadUsersFromFile(), and printSongsOfGenre().
writePlaylistToFile()
void writePlaylistToFile (User * user)
This function writes the data of all the playlists of a user to a .csv file.
Write all the playlists of a user to a file.
Definition at line 1258 of file User.c.
References Song::code, Playlist::isPrivate, MAX_STRING_LENGTH, Playlist::name, User::nickname, User::numberOfPlaylists, Playlist::numberOfSongs, Playlist::ownerNickname, User::playlists, and Playlist::songs.
Referenced by addPlaylist(), addSongToPlaylist(), main(), modifyPlaylist(), removePlaylist(), and removeSongFromPlaylist().