UdaWave: src/modules/User/User.h File Reference
User.h File Reference
Functions to manipulate users and playlists.
#include "../Song/Song.h"
#include "../Utilities/Utilities.h"
Data Structures
struct Playlist
A playlist.
struct User
A user.
Macros
#define MAX_USERS_NUMBER 20
The maximum number of users the software can manage.
#define MAX_PLAYLIST_NUMBER 15
The maximum number of playlist (per user) the software can manage.
Typedefs
typedef struct Playlist Playlist
A playlist.
typedef struct User User
A user.
Functions
void printUsersArray (User *users[], int size)
Print all users data to screen.
void printUserToScreen (User *user)
Print a single user to screen.
void printPlaylistsToScreen (User *user)
Print a user's playlist's list to screen.
void savePlaylistsToFile (User users[], int usersNumber, User *const *currentLoggedUser)
Saves all playlists of a user to file.
void loadPlaylistsFromFile (User usersToModify[], int usersNumber, Song songs[], int currentSongsNumber)
Load all playlists from a file.
void printSongsOfGenre (User users[], int usersNumber, User **currentLoggedUser)
Print all songs of a genre.
void writePlaylistToFile (User *user)
Write all the playlists of a user to a file.
void addPlaylist (User *user, Song songs[], int currentSongSize)
Add a playlist.
void removePlaylist (User *user, Song songs[], int currentSongSize)
Remove a playlist.
void modifyPlaylist (User *user, Song songs[], int currentSongSize)
Remove a playlist.
void addSongToPlaylist (User *user, Song songs[], int currentSongSize)
Add a song to a playlist.
void removeSongFromPlaylist (User *user, Song songs[], int currentSongSize)
Remove a song from a playlist.
User * logIn (User users[], int usersNumber)
Log a user in.
void logOut (User **currentLoggedUser)
Log out from current session.
void modifyFavourites (User **userToModify, User users[], int usersNumber, Song songs[], int songsNumber)
Modify favourite list.
void addFavourite (User **userToModify, User users[], int usersNumber, Song songs[], int songsNumber)
Add a favourite to the favourite list.
void removeFavourite (User **userToModify, User users[], int usersNumber, Song songs[], int songsNumber)
Remove a favourite from the favourite list.
void modifyUser (User users[], int currentSize, User **currentLoggedUser)
Modify a user.
void modifyUsersFile (User users[], int size)
Update users' file.
void printPublicPlaylistsToScreen (User *user, int usersNumber, User *currentLoggedUser)
Print all public playlists.
Playlist ** searchInPlaylists (User users[], int usersNumber, const char *playlistName, const char *ownerName)
Search a playlist.
int getUserIdByNickname (User users[], int size)
Get the id of a user.
int loadUsersFromFile (const char *path, Song *songs, int currentSongNumber, User array[], int maxSize)
Load users' datas from file.
int searchInUsers (User users[], int size, const char *nickname)
Find the user with the given username.
void getNickname (User *usersList, int size, char *nickname)
Insert a nickname;.
int addUser (User users[], int *currentSize, User **currentLoggedUser)
Add a user.
void addToUsersFile (User *user)
Add a user to the users' .csv file.
Detailed Description
Functions to manipulate users and playlists.
This library contains functions that work on users, users' arrays and on playlists, Along with the definitions of users and playlists-related data structures. Some of this functions are based on functions defined in Utilities.h and in Song.h.
Version
0.1
Date
08/may/2018
Authors
Andrea Esposito, Graziano Montanaro
Copyright
No copyright informations provided.
Definition in file User.h.
Macro Definition Documentation
MAX_PLAYLIST_NUMBER
#define MAX_PLAYLIST_NUMBER 15
The maximum number of playlist (per user) the software can manage.
Definition at line 28 of file User.h.
Referenced by addPlaylist(), loadPlaylistsFromFile(), and printPublicPlaylistsToScreen().
MAX_USERS_NUMBER
#define MAX_USERS_NUMBER 20
The maximum number of users the software can manage.
Definition at line 24 of file User.h.
Referenced by addUser(), loadPlaylistsFromFile(), and main().
Typedef Documentation
Playlist
typedef struct Playlist Playlist
A playlist.
The data structure that contains all the informations about a playlist.
User
typedef struct User User
A user.
The data structure that contains all the informations about a user.
Function Documentation
addFavourite()
void addFavourite (User ** userToModify, User users[], int usersNumber, Song songs[], int songsNumber)
Add a favourite to the favourite list.
Parameters
[in] userToModify The user that will be modified.
[in] users The array of users
[in] usersNumber The size of the users' array.
[in] songs The catalog of songs.
[in] songsNumber The number of songs in the catalog.
Add a favourite to the favourite list.
Definition at line 117 of file User.c.
References getChoice(), getInt(), printSongsArray(), printSongToScreen(), and searchSong().
Referenced by modifyFavourites().
addPlaylist()
void addPlaylist (User * user, Song songs[], int currentSongSize)
Add a playlist.
Parameters
[in] user The user whose playlist will be added.
[in] songs The array of songs.
[in] currentSongSize The number of songs.
Add a playlist.
Definition at line 751 of file User.c.
References Song::code, User::favouriteSongs, getChoice(), getInt(), Playlist::isPrivate, MAX_PLAYLIST_NUMBER, MAX_SONGS_NUMBER, Playlist::name, User::nickname, User::numberOfPlaylists, Playlist::numberOfSongs, Playlist::ownerNickname, User::playlists, printSongsArray(), searchInPlaylists(), searchSong(), Playlist::songs, and writePlaylistToFile().
Referenced by main().
addSongToPlaylist()
void addSongToPlaylist (User * user, Song songs[], int currentSongSize)
Add a song to a playlist.
Parameters
[in] user The user whose playlist will be modified.
[in] songs The array of songs.
[in] currentSongSize The number of songs.
Add a song to a playlist.
Definition at line 977 of file User.c.
References User::favouriteSongs, getChoice(), getInt(), MAX_SONGS_NUMBER, User::nickname, printSongsArray(), searchInPlaylists(), searchSong(), and writePlaylistToFile().
Referenced by main().
addToUsersFile()
void addToUsersFile (User * user)
Add a user to the users' .csv file.
Parameters
[in] user User to add to the file.
Add a user to the users' .csv file.
It uses a pointer to the user that it should save for optimization purposes.
Definition at line 299 of file User.c.
References User::birthDate, Song::code, Date::day, doesFileExists(), User::email, User::favouriteSongs, Date::month, User::name, User::nickname, User::numberOfFavouriteSongs, User::sex, User::surname, and Date::year.
Referenced by addUser().
addUser()
int addUser (User users[], int * currentSize, User ** currentLoggedUser)
Add a user.
Parameters
[in] users Array of users.
[in] currentSize Pointer to the current dimension of the array.
[in] currentLoggedUser The current logged user
Returns
The function returns the new dimension of the array if it succeed. If it fails, it returns -1.
Add a user.
Precondition
currentSize should be less than the maximum number of users
Postcondition
If currentSize is greater than the maximum number of users, the function fails and it returns -1.
Definition at line 243 of file User.c.
References addToUsersFile(), User::birthDate, getDate(), getMail(), getName(), getNickname(), getSex(), MAX_USERS_NUMBER, User::numberOfFavouriteSongs, and User::sex.
Referenced by main().
getNickname()
void getNickname (User * usersList, int size, char * nickname)
Insert a nickname;.
Parameters
[in] usersList The list of user where the nickname has to be checked.
[in] size The size of the users' list.
[in] nickname String to where the nickname will be saved.
Insert a nickname;.
Definition at line 1303 of file User.c.
References searchInUsers().
Referenced by addUser().
getUserIdByNickname()
int getUserIdByNickname (User users[], int size)
Get the id of a user.
Parameters
[in] users Array of Users in which to search.
[in] size Size of the array
Returns
It returns the index of the user. It returns -1 if there were errors.
Get the id of a user.
It searches using the nickname, so the function ask the user to insert one (and it checks if it's valid).
Definition at line 59 of file User.c.
References searchInUsers().
Referenced by logIn(), modifyUser(), printPublicPlaylistsToScreen(), printSongsOfGenre(), and savePlaylistsToFile().
loadPlaylistsFromFile()
void loadPlaylistsFromFile (User usersToModify[], int usersNumber, Song songs[], int currentSongsNumber)
Load all playlists from a file.
Parameters
[in] usersToModify The array of users.
[in] usersNumber The number of users.
[in] songs The array of songs.
[in] currentSongsNumber The number of songs.
Load all playlists from a file.
This function gets all the playlists from all users' file and load all the stored informations. Then, it eventually link shared playlists.
Definition at line 625 of file User.c.
References doesFileExists(), Playlist::isPrivate, MAX_CODE_LENGTH, MAX_PLAYLIST_NUMBER, MAX_SONGS_NUMBER, MAX_STRING_LENGTH, MAX_USERS_NUMBER, User::numberOfPlaylists, Playlist::numberOfSongs, User::playlists, searchInUsers(), searchSong(), and Playlist::songs.
Referenced by main().
loadUsersFromFile()
int loadUsersFromFile (const char * path, Song * songs, int currentSongNumber, User array[], int maxSize)
Load users' datas from file.
Parameters
[in] path The path of the file.
[in] songs Songs' array, used to get the list of favourite songs.
[in] currentSongNumber Size of the array of songs.
[in] array The array where datas should be saved.
[in] maxSize The maximum size of the array.
Returns
The function returns the number of read elements. It return -1 in case of any error.
Load users' datas from file.
The informations are stored in an array (a void array, so that it can be used for various data structures).
Precondition
The file should exist.
Postcondition
If the file doesn't exist the function will return -1.
Definition at line 366 of file User.c.
References User::birthDate, Date::day, doesFileExists(), User::favouriteSongs, MAX_CODE_LENGTH, MAX_SONGS_NUMBER, MAX_STRING_LENGTH, Date::month, User::numberOfFavouriteSongs, searchInUsers(), searchSong(), User::sex, and Date::year.
Referenced by main().
logIn()
User* logIn (User users[], int usersNumber)
Log a user in.
Parameters
users The array of users.
usersNumber The number of users.
Returns
A pointer to the new logged user.
Log a user in.
Definition at line 1150 of file User.c.
References User::email, getMail(), getUserIdByNickname(), and MAX_STRING_LENGTH.
Referenced by main().
logOut()
void logOut (User ** currentLoggedUser)
Log out from current session.
Parameters
[out] currentLoggedUser The current logged user that has to be logged out.
Log out from current session.
Definition at line 1169 of file User.c.
Referenced by main().
modifyFavourites()
void modifyFavourites (User ** userToModify, User users[], int usersNumber, Song songs[], int songsNumber)
Modify favourite list.
Parameters
[in] userToModify The user that will be modified.
[in] users The array of users
[in] usersNumber The size of the users' array.
[in] songs The catalog of songs.
[in] songsNumber The number of songs in the catalog.
Modify favourite list.
It asks the user if he/she wants to add or remove a song to/from their favorite list.
Definition at line 88 of file User.c.
References addFavourite(), getInt(), modifyUsersFile(), and removeFavourite().
Referenced by main().
modifyPlaylist()
void modifyPlaylist (User * user, Song songs[], int currentSongSize)
Remove a playlist.
Parameters
[in] user The user whose playlist will be modified.
[in] songs The array of songs.
[in] currentSongSize The number of songs.
Remove a playlist.
Definition at line 909 of file User.c.
References getChoice(), User::nickname, searchInPlaylists(), and writePlaylistToFile().
Referenced by main().
modifyUser()
void modifyUser (User users[], int currentSize, User ** currentLoggedUser)
Modify a user.
Parameters
[in] users The array of users.
[in] currentSize The size of the users' array.
[in] currentLoggedUser The current logged user.
Modify a user.
Definition at line 1181 of file User.c.
References User::birthDate, User::email, getDate(), getMail(), getName(), getSex(), getUserIdByNickname(), modifyUsersFile(), User::name, User::nickname, User::sex, and User::surname.
Referenced by main().
modifyUsersFile()
void modifyUsersFile (User users[], int size)
Update users' file.
Parameters
[in] users The array of users.
[in] size The size of the users' array.
Update users' file.
Definition at line 1221 of file User.c.
Referenced by modifyFavourites(), and modifyUser().
printPlaylistsToScreen()
void printPlaylistsToScreen (User * user)
Print a user's playlist's list to screen.
Parameters
user The "owner" of the playlists that will be printed.
Print a user's playlist's list to screen.
Definition at line 720 of file User.c.
References Song::artist, Playlist::isPrivate, Song::name, Playlist::name, User::name, User::numberOfPlaylists, Playlist::numberOfSongs, Playlist::ownerNickname, User::playlists, Playlist::songs, and User::surname.
Referenced by main().
printPublicPlaylistsToScreen()
void printPublicPlaylistsToScreen (User * user, int usersNumber, User * currentLoggedUser)
Print all public playlists.
Parameters
[in] user The array of users from which it will get all the playlists.
[in] usersNumber The size of the users' array.
[in] currentLoggedUser The current logged user.
printSongsOfGenre()
void printSongsOfGenre (User users[], int usersNumber, User ** currentLoggedUser)
Print all songs of a genre.
Parameters
[in] users The array of users.
[in] usersNumber The number of users.
[in] currentLoggedUser The current logged user.
Print all songs of a genre.
Definition at line 509 of file User.c.
References getUserIdByNickname(), User::nickname, User::numberOfFavouriteSongs, printSongsArray(), quicksort(), searchInUsers(), and searchSong().
Referenced by main().
printUsersArray()
void printUsersArray (User * users[], int size)
Print all users data to screen.
Warning
This function will soon be removed.
Parameters
users The array of users.
size The number of users.
Print all users data to screen.
Definition at line 22 of file User.c.
References printUserToScreen().
Referenced by main(), and printUsersList().
printUserToScreen()
void printUserToScreen (User * user)
Print a single user to screen.
Parameters
user The user that will be printed.
Print a single user to screen.
Definition at line 32 of file User.c.
References Song::artist, User::birthDate, Date::day, User::email, User::favouriteSongs, Date::month, Song::name, User::name, User::nickname, User::numberOfFavouriteSongs, User::sex, User::surname, and Date::year.
Referenced by printUsersArray().
removeFavourite()
void removeFavourite (User ** userToModify, User users[], int usersNumber, Song songs[], int songsNumber)
Remove a favourite from the favourite list.
Parameters
[in] userToModify The user that will be modified.
[in] users The array of users
[in] usersNumber The size of the users' array.
[in] songs The catalog of songs.
[in] songsNumber The number of songs in the catalog.
Remove a favourite from the favourite list.
Definition at line 173 of file User.c.
References getChoice(), getInt(), printSongsArray(), printSongToScreen(), and searchSong().
Referenced by modifyFavourites().
removePlaylist()
void removePlaylist (User * user, Song songs[], int currentSongSize)
Remove a playlist.
Parameters
[in] user The user whose playlist will be removed.
[in] songs The array of songs.
[in] currentSongSize The number of songs.
Remove a playlist.
Definition at line 857 of file User.c.
References Playlist::name, User::nickname, User::numberOfPlaylists, User::playlists, searchInPlaylists(), and writePlaylistToFile().
Referenced by main().
removeSongFromPlaylist()
void removeSongFromPlaylist (User * user, Song songs[], int currentSongSize)
Remove a song from a playlist.
Parameters
[in] user The user whose playlist will be modified.
[in] songs The array of songs.
[in] currentSongSize The number of songs.
Remove a song from a playlist.
Definition at line 1063 of file User.c.
References getChoice(), getInt(), User::nickname, printSongsArray(), printSongToScreen(), searchInPlaylists(), searchSong(), and writePlaylistToFile().
Referenced by main().
savePlaylistsToFile()
void savePlaylistsToFile (User users[], int usersNumber, User *const * currentLoggedUser)
Saves all playlists of a user to file.
Parameters
[in] users The array of users.
[in] usersNumber The number of users.
[in] currentLoggedUser The current logged user
Saves all playlists of a user to file.
This function will work only if the current logged user is the admin. It will create a .csv file which name is the username of the user of whom the playlists will be printed.
Definition at line 571 of file User.c.
References getUserIdByNickname(), and MAX_STRING_LENGTH.
Referenced by main().
searchInPlaylists()
Playlist** searchInPlaylists (User users[], int usersNumber, const char * playlistName, const char * ownerName)
Search a playlist.
Parameters
[in] users The array of users from which it will get all the playlists.
[in] usersNumber The size of the users' array.
[in] playlistName The name of the playlist to search.
[in] ownerName The nickname of the searched playlit's owner.
Returns
A dinamically mapped pointer to a pointer to a Playlist.
Search a playlist.
This function searches trough all the playlists. A playlist is identified by its name and its owner's nickname. The function doesn't search only public or private playlists.
Precondition
The searched playlist should exist
Postcondition
If the playlist doesn't exist, the function will return a null pointer.
Definition at line 1420 of file User.c.
References User::numberOfPlaylists, and User::playlists.
Referenced by addPlaylist(), addSongToPlaylist(), modifyPlaylist(), printPublicPlaylistsToScreen(), removePlaylist(), and removeSongFromPlaylist().
searchInUsers()
int searchInUsers (User users[], int size, const char * nickname)
Find the user with the given username.
Parameters
[in] users The array of user in which the function will search.
[in] size The size of the array.
[in] nickname The nickname that has to be searched.
Returns
The function returns -1 if the nickname isn't in the array. If it is, the function will return the position of the user in the array.
Find the user with the given username.
Postcondition
If the nickname isn't used, the function returns -1
Definition at line 343 of file User.c.
Referenced by getNickname(), getUserIdByNickname(), loadPlaylistsFromFile(), loadUsersFromFile(), and printSongsOfGenre().
writePlaylistToFile()
void writePlaylistToFile (User * user)
Write all the playlists of a user to a file.
Parameters
[in] user The user of whom the playlists will be printed.
Write all the playlists of a user to a file.
Definition at line 1258 of file User.c.
References Song::code, Playlist::isPrivate, MAX_STRING_LENGTH, Playlist::name, User::nickname, User::numberOfPlaylists, Playlist::numberOfSongs, Playlist::ownerNickname, User::playlists, and Playlist::songs.
Referenced by addPlaylist(), addSongToPlaylist(), main(), modifyPlaylist(), removePlaylist(), and removeSongFromPlaylist().