UdaWave: src/modules/Utilities/Utilities.c File Reference
Utilities.c File Reference
Implementation of the functions from Utilities.h.
#include "Utilities.h"
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <ctype.h>
#include <regex.h>
Functions
char getChoice (const char *messageToPrint)
The function gets a boolean choice (YES or NO).
int getInt (int minVal, int maxVal)
This function gets an integer between two values.
bool isNameValid (const char *name)
Check if a given string is a valid name (or surname).
bool checkWithRegEx (const char *regExp, const char *stringToCheck)
Check if a string is can be recognized by a finite state automaton using a regular expression.
bool isMailValid (const char *mail)
This function checks if the string could be a valid email.
int doesFileExists (const char *path)
This function checks if a file exists, trying to open it.
Date getDate ()
This function waits for the user input and checks if the given date is valid.
int isDateValid (Date *date)
This function checks if the date is valid.
int isLeapYear (int year)
This function checks if a given year is leap, using the definition of "leap year".
const char * getMusicGenreName (Genre genre)
This function gets the name of a given genre.
const Genre getMusicGenreIndex (char *genre)
This function gets the genre with a given name.
Genre getGenre ()
This function inserts a music genre.
Sex getSex ()
This function inserts a sex.
void getName (char *name, const char *typeOfName)
This function inserts a name and it checks if there aren't any special characters or digit.
void getMail (char *mail)
This function inserts an email and checks if it could be an email.
Detailed Description
Implementation of the functions from Utilities.h.
This file contains the implementation of the function defined in Utilities.h. It uses the standard C libraries.
Version
0.1
Date
08/may/2018
Authors
Andrea Esposito, Graziano Montanaro
Copyright
No copyright informations provided.
Definition in file Utilities.c.
Function Documentation
checkWithRegEx()
bool checkWithRegEx (const char * regExp, const char * stringToCheck)
Check if a string is can be recognized by a finite state automaton using a regular expression.
Check a string using a regular expression.
Precondition
The regular expression should be valid.
Definition at line 106 of file Utilities.c.
Referenced by isCodeValid(), isMailValid(), and isNameValid().
doesFileExists()
int doesFileExists (const char * path)
This function checks if a file exists, trying to open it.
Check if file exists.
If it didn't worked, it means that the file or the directory couldn't be opened.
Definition at line 149 of file Utilities.c.
Referenced by addToSongsFile(), addToUsersFile(), loadPlaylistsFromFile(), loadSongsFromFile(), and loadUsersFromFile().
getChoice()
char getChoice (const char * messageToPrint)
The function gets a boolean choice (YES or NO).
Get a boolean choice (Y/N).
It print a message (usually a question) on the screen and it waits for the user input. When the user inserts a response, this function converts it to upper case and checks if it is Y (YES) or N (NO). Then, if the given value is valid, it returns it to the caller.
Definition at line 29 of file Utilities.c.
Referenced by addFavourite(), addPlaylist(), addSong(), addSongToPlaylist(), insertDuration(), modifyPlaylist(), printPublicPlaylistsToScreen(), removeFavourite(), and removeSongFromPlaylist().
getDate()
Date getDate ()
This function waits for the user input and checks if the given date is valid.
Insert a date; Prompts the user to insert a date and checks if the given value is valid.
Definition at line 169 of file Utilities.c.
References Date::day, isDateValid(), Date::month, and Date::year.
Referenced by addUser(), and modifyUser().
getGenre()
Genre getGenre ()
This function inserts a music genre.
Insert a music genre.
It prompts the user to insert a music genre (its literal translation). It the given value is valid, the function will return its enum-type value. Otherwise it will ask the user to insert another value.
Definition at line 286 of file Utilities.c.
References getMusicGenreIndex(), getMusicGenreName(), and INVALID_GENRE.
Referenced by addSong(), modifySong(), and searchSongByGenre().
getInt()
int getInt (int minVal, int maxVal)
This function gets an integer between two values.
Get an integer between two values.
If the users inserts a value outside of the given range (or if he input a non-integer value, like a string), the function will ask the user to insert another value, showing an error message. If the input goes well, the function returns the given integer to the caller.
Precondition
minVal and maxVal should be different.
Postcondition
If minVal is equal to maxVal the function will accept all integers.
Definition at line 58 of file Utilities.c.
Referenced by addFavourite(), addPlaylist(), addSong(), addSongToPlaylist(), main(), menu(), modifyFavourites(), modifySong(), removeFavourite(), removeSongFromPlaylist(), and searchForSongs().
getMail()
void getMail (char * mail)
This function inserts an email and checks if it could be an email.
Insert an email.
If it can't, the function will ask for a new email.
Definition at line 367 of file Utilities.c.
References isMailValid().
Referenced by addUser(), logIn(), and modifyUser().
getMusicGenreIndex()
const Genre getMusicGenreIndex (char * genre)
This function gets the genre with a given name.
Get the genre with the given name.
It basically gets the enum-type value from its literal transcription.
Precondition
the name should be a valid genre.
Postcondition
If the name isn't a valid genre the function will return INVALID_GENRE.
Definition at line 265 of file Utilities.c.
References INVALID_GENRE.
Referenced by getGenre(), loadSongsFromFile(), searchSongByGenre(), and test_getMusicGenreIndex().
getMusicGenreName()
const char* getMusicGenreName (Genre genre)
This function gets the name of a given genre.
Get the name of the given genre.
It basically returns a literal transcription for the enum-type value.
Precondition
the genre should be valid.
Postcondition
If the genre is invalid the function will return an empty string.
Definition at line 247 of file Utilities.c.
References INVALID_GENRE.
Referenced by addToSongsFile(), getGenre(), modifySongsFile(), printSongToScreen(), and test_getMusicGenreName().
getName()
void getName (char * name, const char * typeOfName)
This function inserts a name and it checks if there aren't any special characters or digit.
Insert a name; Prompts the user to insert a name and checks if the given value is valid.
If there are, it will ask for another value.
Precondition
typeOfName should be like "name" of "surname".
Definition at line 348 of file Utilities.c.
References isNameValid().
Referenced by addUser(), and modifyUser().
getSex()
Sex getSex ()
This function inserts a sex.
Insert a sex.
It prompts a message and waits for the user input. Then it checks if the given value is a valid genre. If it isn't, the function will ask the user for another value.
Definition at line 316 of file Utilities.c.
Referenced by addUser(), and modifyUser().
isDateValid()
int isDateValid (Date * date)
This function checks if the date is valid.
Check if a date is valid.
Precondition
date Should be a valid date pointer (not NULL).
Definition at line 196 of file Utilities.c.
References Date::day, isLeapYear(), Date::month, and Date::year.
Referenced by getDate(), and test_isDateValid().
isLeapYear()
int isLeapYear (int year)
This function checks if a given year is leap, using the definition of "leap year".
Check if an year is leap.
That is: an year is leap if it can be divided by fir but not by 100 or if it can be divided by 400.
Precondition
year Should be a valid year (positive integer).
Definition at line 229 of file Utilities.c.
Referenced by isDateValid(), and test_isLeapYear().
isMailValid()
bool isMailValid (const char * mail)
This function checks if the string could be a valid email.
Check if the given string could be a valid email.
Warning
This function doesn't check if a mail exists or if it is of a valid hoster. It only checks if a given string is formatted like an e-mail.
Definition at line 136 of file Utilities.c.
References checkWithRegEx().
Referenced by getMail(), and test_isMailValid().
isNameValid()
bool isNameValid (const char * name)
Check if a given string is a valid name (or surname).
Check if a string is a valid name.
It means that the string can't have numbers or non-alphabetic characters in it. Spaces are allowed.
Precondition
name should be a valid (not NULL) char pointer (string).
Definition at line 94 of file Utilities.c.
References checkWithRegEx().
Referenced by getName(), and test_isNameValid().