UdaWave: src/modules/Utilities/Utilities.h File Reference
Utilities.h File Reference
Miscellaneous data structures and functions.
#include <stdbool.h>
Data Structures
struct Date
A date.
Macros
#define MAX_STRING_LENGTH 35
The maximum length of a string (excluding the terminal character).
#define MAX_CODE_LENGTH 5
The maximum length of a code (excluding the terminal character).
Typedefs
typedef char string[MAX_STRING_LENGTH+1]
A string.
typedef enum Genre Genre
Music genres.
typedef enum Sex Sex
A data type to represent someone sex.
typedef struct Date Date
A date.
Enumerations
enum Genre {
BLUES = 0, CLASSIC, HEAVY_METAL, HIP_HOP,
JAZZ, POP, PUNK, ROCK,
INVALID_GENRE = 999
}
Music genres.
enum Sex { MALE = 'M', FEMALE = 'F', OTHER = 'O' }
A data type to represent someone sex.
Functions
Sex getSex ()
Insert a sex.
Genre getGenre ()
Insert a music genre.
const char * getMusicGenreName (Genre genre)
Get the name of the given genre.
const Genre getMusicGenreIndex (char *genre)
Get the genre with the given name.
int doesFileExists (const char *path)
Check if file exists.
bool isMailValid (const char *mail)
Check if the given string could be a valid email.
bool isNameValid (const char *name)
Check if a string is a valid name.
int getInt (int minVal, int maxVal)
Get an integer between two values.
char getChoice (const char *messageToPrint)
Get a boolean choice (Y/N).
bool checkWithRegEx (const char *regExp, const char *stringToCheck)
Check a string using a regular expression.
int isDateValid (Date *date)
Check if a date is valid.
Date getDate ()
Insert a date; Prompts the user to insert a date and checks if the given value is valid.
int isLeapYear (int year)
Check if an year is leap.
void getName (char *name, const char *typeOfName)
Insert a name; Prompts the user to insert a name and checks if the given value is valid.
void getMail (char *mail)
Insert an email.
Detailed Description
Miscellaneous data structures and functions.
This library contains some useful functions and data structures. It is used by other libraries.
Version
0.1
Date
08/may/2018
Authors
Andrea Esposito, Graziano Montanaro
Copyright
No copyright informations provided.
Definition in file Utilities.h.
Macro Definition Documentation
MAX_CODE_LENGTH
#define MAX_CODE_LENGTH 5
The maximum length of a code (excluding the terminal character).
Definition at line 26 of file Utilities.h.
Referenced by loadPlaylistsFromFile(), loadSongsFromFile(), and loadUsersFromFile().
MAX_STRING_LENGTH
#define MAX_STRING_LENGTH 35
The maximum length of a string (excluding the terminal character).
Definition at line 21 of file Utilities.h.
Referenced by loadPlaylistsFromFile(), loadSongsFromFile(), loadUsersFromFile(), logIn(), savePlaylistsToFile(), and writePlaylistToFile().
Typedef Documentation
Date
typedef struct Date Date
A date.
Genre
typedef enum Genre Genre
Music genres.
An enum data type that contains the various music genres.
Sex
typedef enum Sex Sex
A data type to represent someone sex.
string
typedef char string[MAX_STRING_LENGTH+1]
A string.
This definition is used to simplify the creation of strings.
Definition at line 33 of file Utilities.h.
Enumeration Type Documentation
Genre
enum Genre
Music genres.
An enum data type that contains the various music genres.
Enumerator
BLUES
"Blues" music genre.
CLASSIC
"Classic" music genre.
HEAVY_METAL
"Heavy Metal" music genre.
HIP_HOP
"Hip-Hop" music genre.
JAZZ
"Jazz" music genre.
POP
"Pop" music genre.
PUNK
"Punk" music genre.
ROCK
"Rock" music genre.
INVALID_GENRE
Used to represent an invalid music genre.
Definition at line 40 of file Utilities.h.
Sex
enum Sex
A data type to represent someone sex.
Enumerator
MALE
Male sex.
FEMALE
Female sex.
OTHER
Non-Binary sex.
Definition at line 56 of file Utilities.h.
Function Documentation
checkWithRegEx()
bool checkWithRegEx (const char * regExp, const char * stringToCheck)
Check a string using a regular expression.
Parameters
[in] regExp The regular expression.
[in] stringToCheck The string to check.
Returns
true if there are matches, false if there aren't.
Check a string using a regular expression.
Precondition
The regular expression should be valid.
Definition at line 106 of file Utilities.c.
Referenced by isCodeValid(), isMailValid(), and isNameValid().
doesFileExists()
int doesFileExists (const char * path)
Check if file exists.
Parameters
[in] path The path of the file that has to be checked.
Returns
The function returns 0 if the file doesn't exist. If it does, the function returns 1.
Check if file exists.
If it didn't worked, it means that the file or the directory couldn't be opened.
Definition at line 149 of file Utilities.c.
Referenced by addToSongsFile(), addToUsersFile(), loadPlaylistsFromFile(), loadSongsFromFile(), and loadUsersFromFile().
getChoice()
char getChoice (const char * messageToPrint)
Get a boolean choice (Y/N).
This function prompts the user a question and it only accept Y or N (both upper case or lower case) as input.
Parameters
[in] messageToPrint The message to show the user (usually a question).
Returns
The inserted choice (in upper case).
Get a boolean choice (Y/N).
It print a message (usually a question) on the screen and it waits for the user input. When the user inserts a response, this function converts it to upper case and checks if it is Y (YES) or N (NO). Then, if the given value is valid, it returns it to the caller.
Definition at line 29 of file Utilities.c.
Referenced by addFavourite(), addPlaylist(), addSong(), addSongToPlaylist(), insertDuration(), modifyPlaylist(), printPublicPlaylistsToScreen(), removeFavourite(), and removeSongFromPlaylist().
getDate()
Date getDate ()
Insert a date; Prompts the user to insert a date and checks if the given value is valid.
Returns
The inserted date.
Insert a date; Prompts the user to insert a date and checks if the given value is valid.
Definition at line 169 of file Utilities.c.
References Date::day, isDateValid(), Date::month, and Date::year.
Referenced by addUser(), and modifyUser().
getGenre()
Genre getGenre ()
Insert a music genre.
Prompts the user to insert a music genre and checks if the given value is valid.
Returns
The inserted music genre.
Insert a music genre.
It prompts the user to insert a music genre (its literal translation). It the given value is valid, the function will return its enum-type value. Otherwise it will ask the user to insert another value.
Definition at line 286 of file Utilities.c.
References getMusicGenreIndex(), getMusicGenreName(), and INVALID_GENRE.
Referenced by addSong(), modifySong(), and searchSongByGenre().
getInt()
int getInt (int minVal, int maxVal)
Get an integer between two values.
Parameters
[in] minVal The minimum value of the integer.
[in] maxVal The maximum value of the integer.
Returns
The function return the number of the choice.
Get an integer between two values.
If the users inserts a value outside of the given range (or if he input a non-integer value, like a string), the function will ask the user to insert another value, showing an error message. If the input goes well, the function returns the given integer to the caller.
Precondition
minVal and maxVal should be different.
Postcondition
If minVal is equal to maxVal the function will accept all integers.
Definition at line 58 of file Utilities.c.
Referenced by addFavourite(), addPlaylist(), addSong(), addSongToPlaylist(), main(), menu(), modifyFavourites(), modifySong(), removeFavourite(), removeSongFromPlaylist(), and searchForSongs().
getMail()
void getMail (char * mail)
Insert an email.
Prompts the user to insert an email and checks if the given value is valid.
Parameters
[out] mail String where the mail will be saved.
Insert an email.
If it can't, the function will ask for a new email.
Definition at line 367 of file Utilities.c.
References isMailValid().
Referenced by addUser(), logIn(), and modifyUser().
getMusicGenreIndex()
const Genre getMusicGenreIndex (char * genre)
Get the genre with the given name.
Gets a genre name and returns its enum-type value.
Parameters
[in] genre The name from which the function has to get the genre.
Returns
The function returns the genre of the song if the name is valid.
Get the genre with the given name.
It basically gets the enum-type value from its literal transcription.
Precondition
the name should be a valid genre.
Postcondition
If the name isn't a valid genre the function will return INVALID_GENRE.
Definition at line 265 of file Utilities.c.
References INVALID_GENRE.
Referenced by getGenre(), loadSongsFromFile(), searchSongByGenre(), and test_getMusicGenreIndex().
getMusicGenreName()
const char* getMusicGenreName (Genre genre)
Get the name of the given genre.
Gets a genre and returns its literal name.
Parameters
[in] genre The music genre of which the name is wanted.
Returns
The genre name if it is valid. An empty string otherwise.
Get the name of the given genre.
It basically returns a literal transcription for the enum-type value.
Precondition
the genre should be valid.
Postcondition
If the genre is invalid the function will return an empty string.
Definition at line 247 of file Utilities.c.
References INVALID_GENRE.
Referenced by addToSongsFile(), getGenre(), modifySongsFile(), printSongToScreen(), and test_getMusicGenreName().
getName()
void getName (char * name, const char * typeOfName)
Insert a name; Prompts the user to insert a name and checks if the given value is valid.
Parameters
[out] name String to where the name will be saved.
[in] typeOfName A string that will be printed while asking for input (usually "name" or "surname").
Insert a name; Prompts the user to insert a name and checks if the given value is valid.
If there are, it will ask for another value.
Precondition
typeOfName should be like "name" of "surname".
Definition at line 348 of file Utilities.c.
References isNameValid().
Referenced by addUser(), and modifyUser().
getSex()
Sex getSex ()
Insert a sex.
Prompts the user to insert a sex and checks if the given value is valid.
Returns
The inserted sex.
Insert a sex.
It prompts a message and waits for the user input. Then it checks if the given value is a valid genre. If it isn't, the function will ask the user for another value.
Definition at line 316 of file Utilities.c.
Referenced by addUser(), and modifyUser().
isDateValid()
int isDateValid (Date * date)
Check if a date is valid.
Parameters
[in] date Pointer to the date that has to be checked.
Returns
The function returns 1 if the date is valid. If it isn't, the function will return 0.
Check if a date is valid.
Precondition
date Should be a valid date pointer (not NULL).
Definition at line 196 of file Utilities.c.
References Date::day, isLeapYear(), Date::month, and Date::year.
Referenced by getDate(), and test_isDateValid().
isLeapYear()
int isLeapYear (int year)
Check if an year is leap.
Parameters
year The year that should be checked.
Returns
1 if the year is leap, 0 if it isn't.
Check if an year is leap.
That is: an year is leap if it can be divided by fir but not by 100 or if it can be divided by 400.
Precondition
year Should be a valid year (positive integer).
Definition at line 229 of file Utilities.c.
Referenced by isDateValid(), and test_isLeapYear().
isMailValid()
bool isMailValid (const char * mail)
Check if the given string could be a valid email.
Parameters
[in] mail String to check.
Returns
It returns 0 if the string isn't an email. It returns 1 if the string could be an email.
Check if the given string could be a valid email.
Warning
This function doesn't check if a mail exists or if it is of a valid hoster. It only checks if a given string is formatted like an e-mail.
Definition at line 136 of file Utilities.c.
References checkWithRegEx().
Referenced by getMail(), and test_isMailValid().
isNameValid()
bool isNameValid (const char * name)
Check if a string is a valid name.
Parameters
[in] name String that has to be checked.
Returns
The function returns 1 if the name is valid, 0 otherwise.
Check if a string is a valid name.
It means that the string can't have numbers or non-alphabetic characters in it. Spaces are allowed.
Precondition
name should be a valid (not NULL) char pointer (string).
Definition at line 94 of file Utilities.c.
References checkWithRegEx().
Referenced by getName(), and test_isNameValid().